### ISSUE TITLE
amzaing-time-picker does NOT work with "@angular/*": "^7.2.1" and "@angular/material": "^7.2.1"

### ISSUE THREAD

**Issue by st-clair-clarke** [owsolutions/amazing-time-picker#119]
Hi,
I updated to the above libraries and get the following errors:

Errors
Error during template compile of 'AmazingTimePickerModule'
Function calls are not supported in decorators but 'ɵmakeDecorator' was called
in 'NgModule'
'NgModule' calls 'ɵmakeDecorator'.
node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Can
not redeclare block-scoped variable 'ngDevMode'.
node_modules/amazing-time-picker/node_modules/@angular/core/src/render3/ng_dev_m
ode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'
.

**Comment by Enngage** [comment]
It does work in my project using both Angular and Material on version 7.2.1. I would suggest you clean up your node_modules and install clean dependencies.

**Comment by st-clair-clarke** [comment]
removed my node_modules directory and reinstall but same error persists.

**Comment by st-clair-clarke** [comment]
Sorry. Have to remove library. Clean install on another machine still result in the same error. Only library giving me issues. Hope it can be sorted out.
